


general{

}

auth{
pam:enabled = true
fingerprint:enabled = true
}

animations{
enabled = true

  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1

  animation = fade, 1, 6, wind
  animation = fadeIn, 1, 6, winIn
  animation = fadeOut, 1 , 5, winOut
}
#Backgorund
background {
path = /home/Shreeney/Pictures/Profile/Background.jpg

blur_passes = 2
contrast = 1
vibrancy = 0.2
vibrancy_darkness = 0.2
}

input-field{
size = 550, 60
outline_thickness = 2
dots_size = 0.15
dots_spacing = 0.20
dots_center = true
outer_color = rgba(32,214,214,0.50) rgba(154a4aee) 50deg
inner_color = rgba(54, 82, 82,0.20)
rounding = 0.85
position = 0,-50
halign = center
valign = center

fade_on_empty = false
}

label{
monitor = 
text = cmd[update:1000] echo "$(date +"%A, %B %d")"
color = rgb(255, 255, 255)
font_size = 35
halign = center
valign = center
position = 0,200
}

#User

label{
monitor=

text =     $USER
outer_color = rgba(32,214,214,0.50) rgba(154a4aee) 50deg
inner_color = rgba(54, 82, 82,0.20)
rounding = 0.85
position = 0,-50
halign = center
valign = center
position = 0,50
font_size = 20
}
label{
monitor = 
text = cmd[update:1000] echo "$(date +"%-I:%M")"
color = rgba(242, 243, 244, 0.75)
font_size = 95
position = 0,300
halign = center
valign = center

}
